"""add_ai_script_and_transcript_to_communications

Revision ID: 760ee37bead8
Revises: 9e2f403abfc1
Create Date: 2025-12-24 15:42:11.944560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760ee37bead8'
down_revision: Union[str, None] = '9e2f403abfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('ai_script', sa.Text(), nullable=True))
    op.add_column('communications', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communications', 'transcript')
    op.drop_column('communications', 'ai_script')
    # ### end Alembic commands ###
