"""initial

Revision ID: 9e2f403abfc1
Revises: 
Create Date: 2025-12-24 11:28:55.976774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2f403abfc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('cin', sa.String(length=25), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('borrowers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('alternate_phones', sa.JSON(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('permanent_address', sa.JSON(), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=True),
    sa.Column('voter_id', sa.String(length=50), nullable=True),
    sa.Column('driving_license', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('monthly_income', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('preferred_contact_time', sa.String(length=50), nullable=True),
    sa.Column('do_not_call', sa.Boolean(), nullable=True),
    sa.Column('do_not_sms', sa.Boolean(), nullable=True),
    sa.Column('do_not_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('reachability_score', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_borrowers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrowers'))
    )
    op.create_index(op.f('ix_borrowers_external_id'), 'borrowers', ['external_id'], unique=False)
    op.create_index(op.f('ix_borrowers_organization_id'), 'borrowers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_borrowers_primary_phone'), 'borrowers', ['primary_phone'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('agent_settings', sa.JSON(), nullable=True),
    sa.Column('total_cases_handled', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('allowed_start_time', sa.String(length=5), nullable=True),
    sa.Column('allowed_end_time', sa.String(length=5), nullable=True),
    sa.Column('allowed_days', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('target_criteria', sa.JSON(), nullable=True),
    sa.Column('script_template', sa.Text(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('whatsapp_template_id', sa.String(length=100), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('ai_voice', sa.String(length=50), nullable=True),
    sa.Column('ai_language', sa.String(length=10), nullable=True),
    sa.Column('ai_max_turns', sa.Integer(), nullable=True),
    sa.Column('max_attempts_per_borrower', sa.Integer(), nullable=True),
    sa.Column('retry_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('concurrent_calls', sa.Integer(), nullable=True),
    sa.Column('call_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('total_targets', sa.Integer(), nullable=True),
    sa.Column('total_attempted', sa.Integer(), nullable=True),
    sa.Column('total_contacted', sa.Integer(), nullable=True),
    sa.Column('total_successful', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('total_pending', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('results_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_campaigns_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('loans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('external_loan_id', sa.String(length=100), nullable=True),
    sa.Column('loan_account_number', sa.String(length=50), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interest_type', sa.String(length=20), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emi_day', sa.Integer(), nullable=True),
    sa.Column('total_emis', sa.Integer(), nullable=True),
    sa.Column('emis_paid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('outstanding_interest', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outstanding_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overdue_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overdue_emis', sa.Integer(), nullable=True),
    sa.Column('dpd', sa.Integer(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('bucket', sa.String(length=20), nullable=True),
    sa.Column('collection_status', sa.String(length=50), nullable=True),
    sa.Column('is_secured', sa.Boolean(), nullable=True),
    sa.Column('collateral_type', sa.String(length=50), nullable=True),
    sa.Column('collateral_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('collateral_details', sa.JSON(), nullable=True),
    sa.Column('co_applicants', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.JSON(), nullable=True),
    sa.Column('payment_propensity', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('lender_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_loans_borrower_id_borrowers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_loans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_index(op.f('ix_loans_borrower_id'), 'loans', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_loans_external_loan_id'), 'loans', ['external_loan_id'], unique=False)
    op.create_index(op.f('ix_loans_loan_account_number'), 'loans', ['loan_account_number'], unique=False)
    op.create_index(op.f('ix_loans_organization_id'), 'loans', ['organization_id'], unique=False)
    op.create_table('campaign_borrowers',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('outcome_details', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('communication_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_campaign_borrowers_borrower_id_borrowers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_borrowers_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_campaign_borrowers_loan_id_loans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_borrowers'))
    )
    op.create_index(op.f('ix_campaign_borrowers_borrower_id'), 'campaign_borrowers', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_campaign_borrowers_campaign_id'), 'campaign_borrowers', ['campaign_id'], unique=False)
    op.create_table('cases',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up', sa.DateTime(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('successful_contacts', sa.Integer(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('last_contact_outcome', sa.String(length=100), nullable=True),
    sa.Column('ai_handled', sa.Boolean(), nullable=True),
    sa.Column('ai_attempts', sa.Integer(), nullable=True),
    sa.Column('ai_last_conversation', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes_summary', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('auto_close_on_payment', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_cases_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_cases_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cases_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_loan_id'), 'cases', ['loan_id'], unique=False)
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_table('case_assignments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('unassignment_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_case_assignments_agent_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_case_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_assignments_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assignments'))
    )
    op.create_index(op.f('ix_case_assignments_agent_id'), 'case_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_case_id'), 'case_assignments', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_case_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_notes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes'))
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('communications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_duration', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_ai_handled', sa.Boolean(), nullable=True),
    sa.Column('ai_conversation_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('sub_disposition', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_communications_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_communications_borrower_id_borrowers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_communications_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_communications_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_communications_loan_id_loans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_communications_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communications'))
    )
    op.create_index(op.f('ix_communications_borrower_id'), 'communications', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_communications_call_sid'), 'communications', ['call_sid'], unique=False)
    op.create_index(op.f('ix_communications_case_id'), 'communications', ['case_id'], unique=False)
    op.create_index(op.f('ix_communications_loan_id'), 'communications', ['loan_id'], unique=False)
    op.create_index(op.f('ix_communications_organization_id'), 'communications', ['organization_id'], unique=False)
    op.create_table('call_recordings',
    sa.Column('communication_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('transcription_status', sa.String(length=20), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('transcription_segments', sa.JSON(), nullable=True),
    sa.Column('transcription_language', sa.String(length=10), nullable=True),
    sa.Column('transcription_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('entities_mentioned', sa.JSON(), nullable=True),
    sa.Column('compliance_flags', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], name=op.f('fk_call_recordings_communication_id_communications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_recordings')),
    sa.UniqueConstraint('communication_id', name=op.f('uq_call_recordings_communication_id'))
    )
    op.create_table('payment_promises',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('communication_id', sa.UUID(), nullable=True),
    sa.Column('promised_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('fulfilled_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fulfilled_date', sa.Date(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_payment_promises_borrower_id_borrowers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_payment_promises_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], name=op.f('fk_payment_promises_communication_id_communications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_payment_promises_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payment_promises_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_payment_promises_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_promises'))
    )
    op.create_index(op.f('ix_payment_promises_borrower_id'), 'payment_promises', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_payment_promises_loan_id'), 'payment_promises', ['loan_id'], unique=False)
    op.create_index(op.f('ix_payment_promises_organization_id'), 'payment_promises', ['organization_id'], unique=False)
    op.create_table('payments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('external_payment_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charges_component', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('promise_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_payments_borrower_id_borrowers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_payments_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promise_id'], ['payment_promises.id'], name=op.f('fk_payments_promise_id_payment_promises'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_borrower_id'), 'payments', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_payments_external_payment_id'), 'payments', ['external_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_loan_id'), 'payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_loan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_borrower_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_promises_organization_id'), table_name='payment_promises')
    op.drop_index(op.f('ix_payment_promises_loan_id'), table_name='payment_promises')
    op.drop_index(op.f('ix_payment_promises_borrower_id'), table_name='payment_promises')
    op.drop_table('payment_promises')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_communications_organization_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_loan_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_case_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_call_sid'), table_name='communications')
    op.drop_index(op.f('ix_communications_borrower_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_assignments_case_id'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_agent_id'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_loan_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_campaign_borrowers_campaign_id'), table_name='campaign_borrowers')
    op.drop_index(op.f('ix_campaign_borrowers_borrower_id'), table_name='campaign_borrowers')
    op.drop_table('campaign_borrowers')
    op.drop_index(op.f('ix_loans_organization_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_loan_account_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_external_loan_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_borrowers_primary_phone'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_organization_id'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_external_id'), table_name='borrowers')
    op.drop_table('borrowers')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
